version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
  mssql-server:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      TZ: Europe/Rome
      ACCEPT_EULA: "Y"
      MSSQL_PID: Developer
      MSSQL_SA_PASSWORD: p4ssw0rD
    ports:
      - "2433:1433"
    expose:
      - "1433"
    volumes:
      - "mssql-server:/var/opt/mssql"

volumes:
  mssql-server:
